/**
 * app/api/revenue/route.ts
 *
 * GET /api/revenue?userId=xxx
 *
 * Dashboard stats for a booker. Two parallel reads:
 *
 *  1. users/{userId}
 *     Reads totalEvents, ticketsSold, totalRevenue, totalPaidOut directly.
 *     availableBalance = totalRevenue - totalPaidOut (computed here, not stored).
 *
 *  2. events collection (flat)
 *     Queries where organizerId == userId.
 *     Counts how many have status "active" vs "inactive".
 *     Returns the 5 most recent events for the Recent Events table, and a
 *     revenue/tickets time series bucketed by day (14d) / month (12mo) /
 *     year (5y) — built from the same events read, no extra Firestore hit.
 *
 *     Note: each event only stores an aggregate totalRevenue (no per-day
 *     transaction ledger is available here), so the time series buckets by
 *     each event's eventDate — i.e. "revenue generated by events happening
 *     in this period", not literally "money that arrived on this calendar
 *     day". That distinction is preserved in the response shape/labels
 *     rather than faked as transaction-level granularity.
 *
 * This replaces the old nested events/{userId}/userEvents subcollection approach.
 */

import { adminDb } from "@/lib/firebase-admin"
import { verifyAccessToken } from "@/lib/auth-tokens"
import { type NextRequest, NextResponse } from "next/server"
import { computeSalesTrend, todayAndYesterdayKeys } from "@/lib/sales-trend"

export const runtime = "nodejs"
export const dynamic = "force-dynamic"

interface SeriesPoint {
  label: string
  date: string
  revenue: number
  ticketsSold: number
}

function buildDailySeries(events: { eventDate?: string; revenue: number; ticketsSold: number }[]): SeriesPoint[] {
  const days = 14
  const buckets = new Map<string, SeriesPoint>()
  const today = new Date()
  today.setHours(0, 0, 0, 0)

  for (let i = days - 1; i >= 0; i--) {
    const d = new Date(today)
    d.setDate(d.getDate() - i)
    const key = d.toISOString().slice(0, 10)
    buckets.set(key, {
      label: d.toLocaleDateString("en-US", { day: "2-digit" }),
      date: key,
      revenue: 0,
      ticketsSold: 0,
    })
  }

  for (const e of events) {
    if (!e.eventDate) continue
    const key = new Date(e.eventDate).toISOString().slice(0, 10)
    const bucket = buckets.get(key)
    if (bucket) {
      bucket.revenue += e.revenue
      bucket.ticketsSold += e.ticketsSold
    }
  }

  return Array.from(buckets.values())
}

function buildMonthlySeries(events: { eventDate?: string; revenue: number; ticketsSold: number }[]): SeriesPoint[] {
  const months = 12
  const buckets = new Map<string, SeriesPoint>()
  const now = new Date()

  for (let i = months - 1; i >= 0; i--) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1)
    const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`
    buckets.set(key, {
      label: d.toLocaleDateString("en-US", { month: "short" }),
      date: key,
      revenue: 0,
      ticketsSold: 0,
    })
  }

  for (const e of events) {
    if (!e.eventDate) continue
    const d = new Date(e.eventDate)
    const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`
    const bucket = buckets.get(key)
    if (bucket) {
      bucket.revenue += e.revenue
      bucket.ticketsSold += e.ticketsSold
    }
  }

  return Array.from(buckets.values())
}

function buildYearlySeries(events: { eventDate?: string; revenue: number; ticketsSold: number }[]): SeriesPoint[] {
  const years = 5
  const buckets = new Map<string, SeriesPoint>()
  const currentYear = new Date().getFullYear()

  for (let i = years - 1; i >= 0; i--) {
    const y = currentYear - i
    buckets.set(String(y), { label: String(y), date: String(y), revenue: 0, ticketsSold: 0 })
  }

  for (const e of events) {
    if (!e.eventDate) continue
    const y = String(new Date(e.eventDate).getFullYear())
    const bucket = buckets.get(y)
    if (bucket) {
      bucket.revenue += e.revenue
      bucket.ticketsSold += e.ticketsSold
    }
  }

  return Array.from(buckets.values())
}

/**
 * Sums a per-doc field (ticketSales / voteSales) across every
 * admin/{events|votes}/{id}/{date} day-doc for the given ids and date,
 * in parallel. Used to build the portfolio-wide day-over-day trend shown
 * next to Events and Polls on the dashboard (item 9 of the UI renovation)
 * — same day-doc collection the Payouts tab already reads per-event, just
 * summed across every event/poll the booker owns instead of one at a time.
 */
async function sumDaySales(
  adminSubcollection: "events" | "votes",
  ids: string[],
  date: string,
  field: "ticketSales" | "voteSales"
): Promise<number> {
  if (ids.length === 0) return 0
  const snaps = await Promise.all(
    ids.map((id) => adminDb.collection("admin").doc(adminSubcollection).collection(id).doc(date).get())
  )
  return snaps.reduce((sum, snap) => sum + (snap.exists ? (snap.data()?.[field] ?? 0) : 0), 0)
}


export async function GET(request: NextRequest) {
  try {
    // Auth: verify the spotix_at cookie server-side. Deliberately does NOT
    // trust an x-user-id header — this route is reachable directly by any
    // client, and Next middleware never runs on /api/* here, so nothing
    // strips a client-forged header before it reaches this handler. (See
    // app/api/event/one/route.ts and app/api/event/list/route.ts for the
    // same reasoning — this used to trust that header and let anyone read
    // anyone else's revenue data just by setting it.)
    const token = request.cookies.get("spotix_at")?.value
    if (!token) {
      return NextResponse.json(
        { error: "Unauthorized", message: "Not authenticated" },
        { status: 401 }
      )
    }
    let xUserId: string
    try {
      const payload = await verifyAccessToken(token, "spotix-booker")
      xUserId = payload.uid
    } catch {
      return NextResponse.json(
        { error: "Unauthorized", message: "Invalid or expired token" },
        { status: 401 }
      )
    }

    const userId = request.nextUrl.searchParams.get("userId")

    if (!userId) {
      return NextResponse.json({ error: "userId is required" }, { status: 400 })
    }

    // Ensure the requesting user matches the requested userId (prevent cross-user data access)
    if (xUserId !== userId) {
      console.warn(`[api/revenue] User ${xUserId} attempted to access data for ${userId}`)
      return NextResponse.json(
        { error: "Forbidden", message: "You can only access your own data" },
        { status: 403 }
      )
    }

    // ── 1. Read aggregated stats from the user document ───────────────────────
    const userDoc = await adminDb.collection("users").doc(userId).get()

    if (!userDoc.exists) {
      return NextResponse.json({ error: "User not found" }, { status: 404 })
    }

    const userData = userDoc.data()!
    const userName = userData.username || userData.fullName || "Booker"

    const totalEvents: number = userData.totalEvents ?? 0
    const ticketsSold: number = userData.totalTicketsSold ?? 0
    const totalRevenue: number = userData.totalRevenue ?? 0
    const totalPaidOut: number = userData.totalPaidOut ?? 0
    const availableBalance: number = totalRevenue - totalPaidOut

    // ── 2. Query flat events collection by organizerId ────────────────────────
    const eventsSnap = await adminDb
      .collection("events")
      .where("organizerId", "==", userId)
      .orderBy("createdAt", "desc")
      .get()

    let activeEvents = 0
    let inactiveEvents = 0
    const recentEventsData: any[] = []
    const seriesInput: { eventDate?: string; revenue: number; ticketsSold: number }[] = []
    // Only active events feed the day-over-day trend sum below — inactive/
    // ended events don't sell tickets day to day, so reading their day-docs
    // would just add Firestore reads without changing the trend.
    const activeEventIds: string[] = []

    for (const doc of eventsSnap.docs) {
      const d = doc.data()
      if (d.status === "active") activeEventIds.push(doc.id)

      if (d.status === "active") activeEvents++
      else if (d.status === "inactive") inactiveEvents++

      const revenue = d.totalRevenue || 0
      const ticketsSoldForEvent = d.ticketsSold || 0

      recentEventsData.push({
        id: doc.id,
        eventName: d.eventName || "Unnamed Event",
        eventDate: d.eventDate,
        ticketsSold: ticketsSoldForEvent,
        revenue,
        availableBalance: d.availableRevenue ?? revenue - (d.totalPaidOut || 0),
        status: d.status || "inactive",
      })

      seriesInput.push({ eventDate: d.eventDate, revenue, ticketsSold: ticketsSoldForEvent })
    }

    const recentEvents = recentEventsData.slice(0, 5)

    // Day-over-day ticketSales trend across every event the booker owns —
    // reads admin/events/{eventId}/{today|yesterday}, the same day-docs the
    // Payouts tab already reads per-event (see item 9 of the UI renovation).
    const { today, yesterday } = todayAndYesterdayKeys()
    const [eventsSalesToday, eventsSalesYesterday] = await Promise.all([
      sumDaySales("events", activeEventIds, today, "ticketSales"),
      sumDaySales("events", activeEventIds, yesterday, "ticketSales"),
    ])
    const eventsTrend = computeSalesTrend(eventsSalesToday, eventsSalesYesterday)

    const timeSeries = {
      daily: buildDailySeries(seriesInput),
      monthly: buildMonthlySeries(seriesInput),
      yearly: buildYearlySeries(seriesInput),
    }

    // ── 3. Query flat voting (polls) collection by creatorId ──────────────────
    // Same shape/pattern as the events read above — see item 9 of the UI
    // renovation ("dashboard should also feature updates from the polls").
    const pollsSnap = await adminDb
      .collection("voting")
      .where("creatorId", "==", userId)
      .orderBy("createdAt", "desc")
      .get()

    let totalPollRevenue = 0
    let totalVotes = 0
    const recentPollsData: any[] = []
    // Only currently-active polls (now between pollStartDate and
    // pollEndDate) feed the day-over-day trend sum below — mirrors the
    // events-only scoping above. Polls have no stored `status` field, so
    // "active" is computed the same way polls-section.tsx does it
    // client-side: now falls within [pollStartDate, pollEndDate].
    const activePollIds: string[] = []

    for (const doc of pollsSnap.docs) {
      const d = doc.data()
      const pollAmount = d.pollAmount || 0
      const pollCount = d.pollCount || 0
      totalPollRevenue += pollAmount
      totalVotes += pollCount

      const now = Date.now()
      const startMs = d.pollStartDate ? new Date(d.pollStartDate).getTime() : null
      const endMs = d.pollEndDate ? new Date(d.pollEndDate).getTime() : null
      const isActivePoll = (!startMs || now >= startMs) && (!endMs || now <= endMs)
      if (isActivePoll) activePollIds.push(doc.id)

      recentPollsData.push({
        id: doc.id,
        pollName: d.pollName || "Unnamed Poll",
        pollImage: d.pollImage || "",
        pollStartDate: d.pollStartDate || "",
        pollEndDate: d.pollEndDate || "",
        pollAmount,
        pollCount,
        totalPaidOut: d.totalPaidOut || 0,
      })
    }

    const recentPolls = recentPollsData.slice(0, 5)

    // Day-over-day voteSales trend across every poll the booker owns —
    // reads admin/votes/{pollId}/{today|yesterday}, mirroring the events
    // trend above (item 9 of the UI renovation).
    const [pollsSalesToday, pollsSalesYesterday] = await Promise.all([
      sumDaySales("votes", activePollIds, today, "voteSales"),
      sumDaySales("votes", activePollIds, yesterday, "voteSales"),
    ])
    const pollsTrend = computeSalesTrend(pollsSalesToday, pollsSalesYesterday)

    return NextResponse.json({
      stats: {
        totalEvents,
        activeEvents,
        inactiveEvents,
        totalRevenue,
        availableBalance,
        totalPaidOut,
        totalTicketsSold: ticketsSold,
      },
      recentEvents,
      timeSeries,
      eventsTrendPct: eventsTrend.pct,
      eventsTrendTone: eventsTrend.tone,
      pollStats: {
        totalPolls: pollsSnap.size,
        totalPollRevenue,
        totalVotes,
      },
      recentPolls,
      pollsTrendPct: pollsTrend.pct,
      pollsTrendTone: pollsTrend.tone,
      bookerName: userName,
      lastUpdated: Date.now(),
    })
  } catch (error) {
    console.error("Error fetching revenue data:", error)
    return NextResponse.json({ error: "Failed to fetch revenue data" }, { status: 500 })
  }
}
